<?xml version="1.0"?>
<!DOCTYPE automotives [
<!ELEMENT automotives (automotive+)>
<!ELEMENT automotive (id,name,street,city,region?,country,carModels+,cars+)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT carModels (id,name,year,usdPrice,cadPrice,euroPrice,poundPrice)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT usdPrice (#PCDATA)>
<!ELEMENT cadPrice (#PCDATA)>
<!ELEMENT euroPrice (#PCDATA)>
<!ELEMENT poundPrice (#PCDATA)>
<!ELEMENT cars (vin,color,buyer)>
<!ELEMENT vin (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT buyer (#PCDATA)>
]>

<automotives>
    <automotive>
        <id>081df6a8-09fa-40aa-bc00-27ab14a9f216</id>
        <name>Chevrolet</name>
        <street>4659 American Lane</street>
        <city>Montaigu</city>
        <region>Pays de la Loire</region>
        <country>France</country>
        <carModels>
            <id>9facefb2-503f-4a21-96e3-272fffadf5ed</id>
            <name>MPV</name>
            <year>2000</year>
            <usdPrice>$35852.42</usdPrice>
            <cadPrice>$40615.71</cadPrice>
            <euroPrice>€33338,73</euroPrice>
            <poundPrice>£92221.34</poundPrice>
        </carModels>
        <carModels>
            <id>bcb685e0-8315-4015-91e4-44257b7d1e91</id>
            <name>Camry</name>
            <year>2003</year>
            <usdPrice>$39688.38</usdPrice>
            <cadPrice>$76556.45</cadPrice>
            <euroPrice>€99534,56</euroPrice>
            <poundPrice>£76670.26</poundPrice>
        </carModels>
        <carModels>
            <id>6b222199-1992-4168-98cc-77a194072be6</id>
            <name>M</name>
            <year>2011</year>
            <usdPrice>$74122.16</usdPrice>
            <cadPrice>$98345.04</cadPrice>
            <euroPrice>€47275,87</euroPrice>
            <poundPrice>£60432.34</poundPrice>
        </carModels>
        <cars>
            <vin>JTDKN3DU8F0938961</vin>
            <color>Violet</color>
            <buyer>rmissenden1x@cbslocal.com</buyer>
        </cars>
        <cars>
            <vin>WP0CA2A84FS421937</vin>
            <color>Aquamarine</color>
            <buyer>hhazeldene1y@admin.ch</buyer>
        </cars>
        <cars>
            <vin>WAUEF98E37A023346</vin>
            <color>Fuscia</color>
            <buyer>mwilliscroft1z@spiegel.de</buyer>
        </cars>
        <cars>
            <vin>19UUA9E50CA543243</vin>
            <color>Teal</color>
            <buyer>tcopestick20@unc.edu</buyer>
        </cars>
        <cars>
            <vin>1NXBU4EE7AZ391940</vin>
            <color>Purple</color>
            <buyer>jbaudrey21@diigo.com</buyer>
        </cars>
        <cars>
            <vin>3C6JD6EP7CG059927</vin>
            <color>Turquoise</color>
            <buyer>stunnah22@spotify.com</buyer>
        </cars>
    </automotive>
    <automotive>
        <id>6723f9df-0c01-4000-b803-368b41077d4a</id>
        <name>Honda</name>
        <street>4140 Fordem Alley</street>
        <city>Sogcho</city>
        <country>South Korea</country>
        <carModels>
            <id>a1b457de-73f7-4c7f-b00c-926bcfa6892b</id>
            <name>Sterling</name>
            <year>1991</year>
            <usdPrice>$77835.38</usdPrice>
            <cadPrice>$10632.39</cadPrice>
            <euroPrice>€43923,91</euroPrice>
            <poundPrice>£39931.27</poundPrice>
        </carModels>
        <carModels>
            <id>0c8c3aa4-6f43-4a4f-b4e4-711921563792</id>
            <name>Express 2500</name>
            <year>2002</year>
            <usdPrice>$40634.07</usdPrice>
            <cadPrice>$96011.72</cadPrice>
            <euroPrice>€50872,75</euroPrice>
            <poundPrice>£40639.78</poundPrice>
        </carModels>
        <carModels>
            <id>219a4ba2-eb4d-48fa-80fe-b03e386492a1</id>
            <name>200</name>
            <year>2011</year>
            <usdPrice>$22427.39</usdPrice>
            <cadPrice>$62815.28</cadPrice>
            <euroPrice>€83212,88</euroPrice>
            <poundPrice>£86678.96</poundPrice>
        </carModels>
        <cars>
            <vin>3VWML7AJ7CM158522</vin>
            <color>Crimson</color>
            <buyer>ayewdell1s@usatoday.com</buyer>
        </cars>
        <cars>
            <vin>WBAAZ33415K491391</vin>
            <color>Puce</color>
            <buyer>aslyme1t@youtube.com</buyer>
        </cars>
        <cars>
            <vin>1N6AA0CA6BN857626</vin>
            <color>Mauv</color>
            <buyer>sroscamp1u@newsvine.com</buyer>
        </cars>
        <cars>
            <vin>1FTNF2A58AE079509</vin>
            <color>Khaki</color>
            <buyer>dpickavance1v@friendfeed.com</buyer>
        </cars>
        <cars>
            <vin>WVGAV7AX1BW901951</vin>
            <color>Pink</color>
            <buyer>ndulake1w@google.nl</buyer>
        </cars>
    </automotive>
    <automotive>
        <id>ea7f382b-d285-47f7-a671-f2c1e4b2ed0d</id>
        <name>Lincoln</name>
        <street>30 Barby Alley</street>
        <city>Noyon</city>
        <region>Picardie</region>
        <country>France</country>
        <carModels>
            <id>e81573c7-a7f2-488c-ab55-4a059c05119c</id>
            <name>Thunderbird</name>
            <year>1989</year>
            <usdPrice>$91827.63</usdPrice>
            <cadPrice>$95758.28</cadPrice>
            <euroPrice>€35276,93</euroPrice>
            <poundPrice>£94533.67</poundPrice>
        </carModels>
        <carModels>
            <id>ee579150-4e7b-43ce-be61-10847fdf607a</id>
            <name>Miata MX-5</name>
            <year>2003</year>
            <usdPrice>$70663.60</usdPrice>
            <cadPrice>$84159.72</cadPrice>
            <euroPrice>€32672,77</euroPrice>
            <poundPrice>£16631.85</poundPrice>
        </carModels>
        <carModels>
            <id>7014e302-2e81-4c61-b02a-9ddf9437e2c8</id>
            <name>Ram Van B350</name>
            <year>1992</year>
            <usdPrice>$14259.75</usdPrice>
            <cadPrice>$50843.92</cadPrice>
            <euroPrice>€20204,36</euroPrice>
            <poundPrice>£77350.43</poundPrice>
        </carModels>
        <cars>
            <vin>WAUNF78P38A124572</vin>
            <color>Blue</color>
            <buyer>astreeter1n@privacy.gov.au</buyer>
        </cars>
        <cars>
            <vin>WAUAF78E18A009563</vin>
            <color>Turquoise</color>
            <buyer>jtemby1o@xing.com</buyer>
        </cars>
        <cars>
            <vin>KMHFH4JG1FA970458</vin>
            <color>Aquamarine</color>
            <buyer>kvaller1p@4shared.com</buyer>
        </cars>
        <cars>
            <vin>WAU2GBFC2CN230998</vin>
            <color>Red</color>
            <buyer>acrosswaite1q@wsj.com</buyer>
        </cars>
        <cars>
            <vin>WAUVF98K89A984565</vin>
            <color>Teal</color>
            <buyer>lnicholl1r@godaddy.com</buyer>
        </cars>
    </automotive>
    <automotive>
        <id>74c4cb1a-65c3-4012-af6d-7dd921532ad7</id>
        <name>Ford</name>
        <street>820 Valley Edge Street</street>
        <city>La Seyne-sur-Mer</city>
        <region>Provence-Alpes-Côte d'Azur</region>
        <country>France</country>
        <carModels>
            <id>b4750632-3546-442c-b303-485360818dc5</id>
            <name>Explorer</name>
            <year>2013</year>
            <usdPrice>$57828.44</usdPrice>
            <cadPrice>$63983.16</cadPrice>
            <euroPrice>€20016,38</euroPrice>
            <poundPrice>£44682.78</poundPrice>
        </carModels>
        <carModels>
            <id>30ae99bf-02d0-465c-91ee-9f514479ad62</id>
            <name>300M</name>
            <year>2002</year>
            <usdPrice>$27315.20</usdPrice>
            <cadPrice>$68159.92</cadPrice>
            <euroPrice>€74252,65</euroPrice>
            <poundPrice>£55092.93</poundPrice>
        </carModels>
        <carModels>
            <id>6b365628-92a7-4745-a7ea-1d6d8ebb4f02</id>
            <name>Trans Sport</name>
            <year>1995</year>
            <usdPrice>$93029.12</usdPrice>
            <cadPrice>$78635.77</cadPrice>
            <euroPrice>€67850,56</euroPrice>
            <poundPrice>£52737.17</poundPrice>
        </carModels>
        <cars>
            <vin>1J4PN2GK8AW403803</vin>
            <color>Purple</color>
            <buyer>dmottershaw1i@senate.gov</buyer>
        </cars>
        <cars>
            <vin>5TDBW5G18FS612858</vin>
            <color>Maroon</color>
            <buyer>rdesesquelle1j@issuu.com</buyer>
        </cars>
        <cars>
            <vin>WBS3C9C53FP537356</vin>
            <color>Fuscia</color>
            <buyer>mroubottom1k@quantcast.com</buyer>
        </cars>
        <cars>
            <vin>1GD01ZCG6CF361384</vin>
            <color>Violet</color>
            <buyer>nhenrot1l@psu.edu</buyer>
        </cars>
        <cars>
            <vin>1FTWW3A58AE430459</vin>
            <color>Violet</color>
            <buyer>qkelloch1m@sitemeter.com</buyer>
        </cars>
    </automotive>
    <automotive>
        <id>485a6a77-c251-4920-b00d-a9c96f8b0037</id>
        <name>Chrysler</name>
        <street>8 Killdeer Place</street>
        <city>Creil</city>
        <region>Picardie</region>
        <country>France</country>
        <carModels>
            <id>81af56c0-0b29-4f32-89c3-42f899c271f9</id>
            <name>Ridgeline</name>
            <year>2011</year>
            <usdPrice>$63461.61</usdPrice>
            <cadPrice>$53755.91</cadPrice>
            <euroPrice>€10147,12</euroPrice>
            <poundPrice>£48835.51</poundPrice>
        </carModels>
        <carModels>
            <id>ca04026c-429b-4822-9334-2f37f4e14646</id>
            <name>RX Hybrid</name>
            <year>2010</year>
            <usdPrice>$10441.06</usdPrice>
            <cadPrice>$19802.60</cadPrice>
            <euroPrice>€50283,48</euroPrice>
            <poundPrice>£98516.76</poundPrice>
        </carModels>
        <carModels>
            <id>2a046362-94fa-4fad-9971-ee8793bce80a</id>
            <name>Sonoma Club Coupe</name>
            <year>1994</year>
            <usdPrice>$87244.40</usdPrice>
            <cadPrice>$18099.62</cadPrice>
            <euroPrice>€38217,23</euroPrice>
            <poundPrice>£26810.96</poundPrice>
        </carModels>
        <cars>
            <vin>5LMJJ2H50DE219118</vin>
            <color>Red</color>
            <buyer>lbane1e@hud.gov</buyer>
        </cars>
        <cars>
            <vin>WDDHH8JB4FB808428</vin>
            <color>Violet</color>
            <buyer>aimpleton1f@ameblo.jp</buyer>
        </cars>
        <cars>
            <vin>WAULC68E25A513742</vin>
            <color>Goldenrod</color>
            <buyer>seymer1g@microsoft.com</buyer>
        </cars>
        <cars>
            <vin>WAUEH98E16A740482</vin>
            <color>Orange</color>
            <buyer>jleaves1h@rediff.com</buyer>
        </cars>
    </automotive>
    <automotive>
        <id>fc8c76c4-9a64-44e8-ba64-f17565d9a467</id>
        <name>Lamborghini</name>
        <street>959 Rusk Terrace</street>
        <city>Chalon-sur-Saône</city>
        <region>Bourgogne</region>
        <country>France</country>
        <carModels>
            <id>ec33ad8c-bef4-4daf-9959-2489c84d61c3</id>
            <name>Alliance</name>
            <year>1983</year>
            <usdPrice>$77436.71</usdPrice>
            <cadPrice>$88109.35</cadPrice>
            <euroPrice>€50198,90</euroPrice>
            <poundPrice>£11096.50</poundPrice>
        </carModels>
        <carModels>
            <id>d20479a0-2af0-4bf5-b676-64817e83a5fb</id>
            <name>Riviera</name>
            <year>1991</year>
            <usdPrice>$50122.72</usdPrice>
            <cadPrice>$56456.77</cadPrice>
            <euroPrice>€88934,08</euroPrice>
            <poundPrice>£19085.89</poundPrice>
        </carModels>
        <carModels>
            <id>6988d761-270e-4d41-9d4f-a3777aeaba05</id>
            <name>H1</name>
            <year>2002</year>
            <usdPrice>$40294.99</usdPrice>
            <cadPrice>$25707.13</cadPrice>
            <euroPrice>€68592,98</euroPrice>
            <poundPrice>£96691.41</poundPrice>
        </carModels>
        <cars>
            <vin>WAUUL78E95A440024</vin>
            <color>Mauv</color>
            <buyer>lbearfoot19@people.com.cn</buyer>
        </cars>
        <cars>
            <vin>1C6RD6HT1CS162250</vin>
            <color>Teal</color>
            <buyer>jbrisker1a@msu.edu</buyer>
        </cars>
        <cars>
            <vin>WBA3T1C50FP139172</vin>
            <color>Purple</color>
            <buyer>menrico1b@tuttocitta.it</buyer>
        </cars>
        <cars>
            <vin>1G6AF5SX1D0448749</vin>
            <color>Violet</color>
            <buyer>rrenish1c@mysql.com</buyer>
        </cars>
        <cars>
            <vin>1ZVBP8JZ2E5399226</vin>
            <color>Puce</color>
            <buyer>myukhnov1d@alexa.com</buyer>
        </cars>
    </automotive>
    <automotive>
        <id>b22e2006-4461-4b6f-b5ab-24627869c943</id>
        <name>Toyota</name>
        <street>1062 Northridge Avenue</street>
        <city>Gap</city>
        <region>Provence-Alpes-Côte d'Azur</region>
        <country>France</country>
        <carModels>
            <id>a2b33f24-dd00-4e7c-aa17-8c93dffaa0cf</id>
            <name>Firebird</name>
            <year>2002</year>
            <usdPrice>$44301.34</usdPrice>
            <cadPrice>$32592.34</cadPrice>
            <euroPrice>€33547,31</euroPrice>
            <poundPrice>£27766.08</poundPrice>
        </carModels>
        <carModels>
            <id>4d74d75a-7acf-4d7d-a397-9579e9501444</id>
            <name>Mustang</name>
            <year>1989</year>
            <usdPrice>$93278.35</usdPrice>
            <cadPrice>$39562.19</cadPrice>
            <euroPrice>€55058,77</euroPrice>
            <poundPrice>£57686.89</poundPrice>
        </carModels>
        <carModels>
            <id>3577ad54-36c4-4220-a32b-2546fe91cf6c</id>
            <name>Mystique</name>
            <year>1997</year>
            <usdPrice>$16897.33</usdPrice>
            <cadPrice>$36608.90</cadPrice>
            <euroPrice>€28992,90</euroPrice>
            <poundPrice>£28643.98</poundPrice>
        </carModels>
        <cars>
            <vin>1GYS4JEF9BR097398</vin>
            <color>Fuscia</color>
            <buyer>eskentelbury14@google.es</buyer>
        </cars>
        <cars>
            <vin>JHMFA3F2XAS772155</vin>
            <color>Violet</color>
            <buyer>ldarrigone15@prweb.com</buyer>
        </cars>
        <cars>
            <vin>WA1KK78R49A402300</vin>
            <color>Puce</color>
            <buyer>mpavlasek16@bandcamp.com</buyer>
        </cars>
        <cars>
            <vin>WAUKFAFL5CA367972</vin>
            <color>Turquoise</color>
            <buyer>bcarse17@cam.ac.uk</buyer>
        </cars>
        <cars>
            <vin>1FTMF1EW7AF880063</vin>
            <color>Puce</color>
            <buyer>vchivrall18@theguardian.com</buyer>
        </cars>
    </automotive>
    <automotive>
        <id>b2e9091c-9882-491b-a674-0267751be06f</id>
        <name>Mitsubishi</name>
        <street>97633 Jackson Center</street>
        <city>Houston</city>
        <region>Texas</region>
        <country>United States</country>
        <carModels>
            <id>11e9ea60-4fed-422f-83ad-2603053884ae</id>
            <name>Wrangler</name>
            <year>2012</year>
            <usdPrice>$27390.99</usdPrice>
            <cadPrice>$22569.61</cadPrice>
            <euroPrice>€67857,58</euroPrice>
            <poundPrice>£72816.35</poundPrice>
        </carModels>
        <carModels>
            <id>78b67884-1be0-4f27-b6b9-61bca357ab5d</id>
            <name>CL-Class</name>
            <year>2012</year>
            <usdPrice>$19723.00</usdPrice>
            <cadPrice>$41987.23</cadPrice>
            <euroPrice>€30528,66</euroPrice>
            <poundPrice>£69807.68</poundPrice>
        </carModels>
        <carModels>
            <id>772a0a35-72a2-4309-b985-2f98cd663101</id>
            <name>Golf</name>
            <year>1995</year>
            <usdPrice>$41588.26</usdPrice>
            <cadPrice>$46995.00</cadPrice>
            <euroPrice>€56153,75</euroPrice>
            <poundPrice>£73142.71</poundPrice>
        </carModels>
        <cars>
            <vin>SCBFR7ZA7CC524370</vin>
            <color>Purple</color>
            <buyer>frivilisz@indiatimes.com</buyer>
        </cars>
        <cars>
            <vin>WAUDFAFLXBA445766</vin>
            <color>Goldenrod</color>
            <buyer>samorts10@hexun.com</buyer>
        </cars>
        <cars>
            <vin>2B3CK2CV5AH266252</vin>
            <color>Violet</color>
            <buyer>bcolleer11@squarespace.com</buyer>
        </cars>
        <cars>
            <vin>NM0AE8F7XE1656374</vin>
            <color>Violet</color>
            <buyer>mbonass12@google.de</buyer>
        </cars>
        <cars>
            <vin>5N1AN0NU5AC947550</vin>
            <color>Turquoise</color>
            <buyer>jinkin13@github.io</buyer>
        </cars>
    </automotive>
    <automotive>
        <id>275fda79-516d-44c5-ab72-d4c4874833eb</id>
        <name>Cadillac</name>
        <street>56 Heffernan Place</street>
        <city>Arras</city>
        <region>Nord-Pas-de-Calais</region>
        <country>France</country>
        <carModels>
            <id>b8c784d1-0993-4586-8ec2-9316a649c54c</id>
            <name>Prizm</name>
            <year>1997</year>
            <usdPrice>$72413.64</usdPrice>
            <cadPrice>$91227.65</cadPrice>
            <euroPrice>€21909,72</euroPrice>
            <poundPrice>£41593.23</poundPrice>
        </carModels>
        <carModels>
            <id>40b2b19f-fbae-4aeb-ac82-01d06cf9ef25</id>
            <name>Defender</name>
            <year>1995</year>
            <usdPrice>$68341.38</usdPrice>
            <cadPrice>$29247.80</cadPrice>
            <euroPrice>€36086,04</euroPrice>
            <poundPrice>£94567.80</poundPrice>
        </carModels>
        <carModels>
            <id>5e1b284a-6172-485e-bfd8-5a9b69e62958</id>
            <name>Sunbird</name>
            <year>1988</year>
            <usdPrice>$50913.38</usdPrice>
            <cadPrice>$32835.18</cadPrice>
            <euroPrice>€71301,49</euroPrice>
            <poundPrice>£71629.21</poundPrice>
        </carModels>
        <cars>
            <vin>3C6JD6BP8CG986455</vin>
            <color>Green</color>
            <buyer>okuncu@discuz.net</buyer>
        </cars>
        <cars>
            <vin>WBA5A7C51FD606778</vin>
            <color>Aquamarine</color>
            <buyer>rsantenv@tinypic.com</buyer>
        </cars>
        <cars>
            <vin>4T1BD1EB8FU859508</vin>
            <color>Indigo</color>
            <buyer>nchaggw@go.com</buyer>
        </cars>
        <cars>
            <vin>JA32X8HW7DU297437</vin>
            <color>Maroon</color>
            <buyer>nyoellx@deviantart.com</buyer>
        </cars>
        <cars>
            <vin>4T3BA3BB8AU048820</vin>
            <color>Blue</color>
            <buyer>meburahy@dyndns.org</buyer>
        </cars>
    </automotive>
    <automotive>
        <id>6a859745-9392-43e1-97de-25bfc0569742</id>
        <name>GMC</name>
        <street>51557 Grasskamp Crossing</street>
        <city>Annecy</city>
        <region>Rhône-Alpes</region>
        <country>France</country>
        <carModels>
            <id>50a3fa57-e3e3-4d79-94a8-ea15f604f042</id>
            <name>Passport</name>
            <year>1997</year>
            <usdPrice>$37484.57</usdPrice>
            <cadPrice>$63691.54</cadPrice>
            <euroPrice>€75326,90</euroPrice>
            <poundPrice>£14916.26</poundPrice>
        </carModels>
        <carModels>
            <id>5976b6f4-87f3-4c37-9f90-b14468b8164e</id>
            <name>Talon</name>
            <year>1998</year>
            <usdPrice>$50778.85</usdPrice>
            <cadPrice>$32493.59</cadPrice>
            <euroPrice>€24999,34</euroPrice>
            <poundPrice>£23428.99</poundPrice>
        </carModels>
        <carModels>
            <id>37c58d92-256c-4574-9bb7-5efa73ff160b</id>
            <name>Odyssey</name>
            <year>2007</year>
            <usdPrice>$78863.61</usdPrice>
            <cadPrice>$31236.27</cadPrice>
            <euroPrice>€38328,87</euroPrice>
            <poundPrice>£61452.13</poundPrice>
        </carModels>
        <cars>
            <vin>1FMEU8FEXAU382830</vin>
            <color>Aquamarine</color>
            <buyer>tdownhamp@photobucket.com</buyer>
        </cars>
        <cars>
            <vin>WAURVAFA2AN180226</vin>
            <color>Blue</color>
            <buyer>mpalmbyq@twitpic.com</buyer>
        </cars>
        <cars>
            <vin>1G6AG5RXXF0337705</vin>
            <color>Puce</color>
            <buyer>pcappelr@theatlantic.com</buyer>
        </cars>
        <cars>
            <vin>5NPEB4AC9DH048136</vin>
            <color>Pink</color>
            <buyer>nkerrs@webs.com</buyer>
        </cars>
        <cars>
            <vin>SCBBR93W29C479510</vin>
            <color>Blue</color>
            <buyer>ojanset@cyberchimps.com</buyer>
        </cars>
    </automotive>
    <automotive>
        <id>97a0360a-2611-45f1-877b-f18c2cb6b998</id>
        <name>Pontiac</name>
        <street>59361 Sundown Crossing</street>
        <city>Duluth</city>
        <region>Georgia</region>
        <country>United States</country>
        <carModels>
            <id>bf91d55f-1763-4fe3-a400-162fb8b1700a</id>
            <name>Trooper</name>
            <year>1993</year>
            <usdPrice>$88353.26</usdPrice>
            <cadPrice>$39414.65</cadPrice>
            <euroPrice>€30468,59</euroPrice>
            <poundPrice>£14494.00</poundPrice>
        </carModels>
        <carModels>
            <id>9a75432d-c2e1-4688-b917-7779c98a2d0f</id>
            <name>CX-9</name>
            <year>2011</year>
            <usdPrice>$53627.47</usdPrice>
            <cadPrice>$94442.87</cadPrice>
            <euroPrice>€99368,82</euroPrice>
            <poundPrice>£14091.59</poundPrice>
        </carModels>
        <carModels>
            <id>bc33df86-0f35-4dfb-a370-afb9c5a1ae2b</id>
            <name>Liberty</name>
            <year>2011</year>
            <usdPrice>$51203.74</usdPrice>
            <cadPrice>$76059.23</cadPrice>
            <euroPrice>€31646,26</euroPrice>
            <poundPrice>£24225.92</poundPrice>
        </carModels>
        <cars>
            <vin>WA1CGBFE5BD708287</vin>
            <color>Khaki</color>
            <buyer>epeirpointk@earthlink.net</buyer>
        </cars>
        <cars>
            <vin>2G4WB55K931473198</vin>
            <color>Aquamarine</color>
            <buyer>mrylandsl@businessinsider.com</buyer>
        </cars>
        <cars>
            <vin>JN1AZ4EH7BM905267</vin>
            <color>Aquamarine</color>
            <buyer>rfretterm@quantcast.com</buyer>
        </cars>
        <cars>
            <vin>SAJWA6E71E8805080</vin>
            <color>Red</color>
            <buyer>kjankiewiczn@amazon.co.jp</buyer>
        </cars>
        <cars>
            <vin>1GYUCDEF3AR532654</vin>
            <color>Yellow</color>
            <buyer>mlocktono@ox.ac.uk</buyer>
        </cars>
    </automotive>
    <automotive>
        <id>3555b263-c8a4-4e81-b787-13e407adcaf4</id>
        <name>Mercedes-Benz</name>
        <street>69619 Farragut Place</street>
        <city>Pensacola</city>
        <region>Florida</region>
        <country>United States</country>
        <carModels>
            <id>0161cdb2-94a8-484e-aad4-d4c113377f8a</id>
            <name>Cayman</name>
            <year>2010</year>
            <usdPrice>$38934.34</usdPrice>
            <cadPrice>$61900.35</cadPrice>
            <euroPrice>€35286,24</euroPrice>
            <poundPrice>£22593.86</poundPrice>
        </carModels>
        <carModels>
            <id>477cd8e7-1d69-4e6a-b3e1-253245c45a74</id>
            <name>LS</name>
            <year>1995</year>
            <usdPrice>$78549.09</usdPrice>
            <cadPrice>$34991.86</cadPrice>
            <euroPrice>€96730,98</euroPrice>
            <poundPrice>£28497.64</poundPrice>
        </carModels>
        <carModels>
            <id>b378a09c-28fc-4d3d-8dbc-97fa24d3b5be</id>
            <name>3500</name>
            <year>2011</year>
            <usdPrice>$91279.42</usdPrice>
            <cadPrice>$73675.26</cadPrice>
            <euroPrice>€56946,56</euroPrice>
            <poundPrice>£57657.19</poundPrice>
        </carModels>
        <cars>
            <vin>2G4GN5EK9C9998789</vin>
            <color>Mauv</color>
            <buyer>nromaintf@wunderground.com</buyer>
        </cars>
        <cars>
            <vin>1G4GD5ED4BF376174</vin>
            <color>Mauv</color>
            <buyer>mmcgaughayg@redcross.org</buyer>
        </cars>
        <cars>
            <vin>1G4HP52K654786120</vin>
            <color>Maroon</color>
            <buyer>jaslinh@auda.org.au</buyer>
        </cars>
        <cars>
            <vin>WDDHF5KB0EA157872</vin>
            <color>Purple</color>
            <buyer>kdimitrescui@lulu.com</buyer>
        </cars>
        <cars>
            <vin>3C4PDDEG5DT348904</vin>
            <color>Yellow</color>
            <buyer>ehuguenetj@examiner.com</buyer>
        </cars>
    </automotive>
    <automotive>
        <id>d9dcc23c-c0bb-4598-bdb4-32e2431d6bae</id>
        <name>Dodge</name>
        <street>0 Northview Lane</street>
        <city>Maizuru</city>
        <country>Japan</country>
        <carModels>
            <id>5217685e-9a49-47e9-91d4-6f1d449fbbbe</id>
            <name>Ram Van 3500</name>
            <year>2003</year>
            <usdPrice>$74298.10</usdPrice>
            <cadPrice>$99669.69</cadPrice>
            <euroPrice>€67548,01</euroPrice>
            <poundPrice>£95455.36</poundPrice>
        </carModels>
        <carModels>
            <id>d5196f96-9b54-485b-aa26-9c3f420a9a0c</id>
            <name>GTO</name>
            <year>2006</year>
            <usdPrice>$82668.20</usdPrice>
            <cadPrice>$49687.96</cadPrice>
            <euroPrice>€24723,55</euroPrice>
            <poundPrice>£82249.33</poundPrice>
        </carModels>
        <carModels>
            <id>903cd852-125d-4bda-b0c2-86371cb97637</id>
            <name>612 Scaglietti</name>
            <year>2007</year>
            <usdPrice>$38686.66</usdPrice>
            <cadPrice>$84396.72</cadPrice>
            <euroPrice>€59104,79</euroPrice>
            <poundPrice>£44888.81</poundPrice>
        </carModels>
        <cars>
            <vin>1N6AA0CH5FN487935</vin>
            <color>Aquamarine</color>
            <buyer>dbirtleya@craigslist.org</buyer>
        </cars>
        <cars>
            <vin>1C3CCBBB5CN430178</vin>
            <color>Maroon</color>
            <buyer>rtingcombb@arizona.edu</buyer>
        </cars>
        <cars>
            <vin>1FMHK7B80CG283142</vin>
            <color>Green</color>
            <buyer>jtwinnc@bigcartel.com</buyer>
        </cars>
        <cars>
            <vin>3D73Y3HL1BG734768</vin>
            <color>Orange</color>
            <buyer>bduelld@last.fm</buyer>
        </cars>
        <cars>
            <vin>1N4AL2EP9DC930552</vin>
            <color>Pink</color>
            <buyer>acholdcrofte@apache.org</buyer>
        </cars>
    </automotive>
    <automotive>
        <id>b2f54f87-6ba9-4727-bffd-15fbc91bf74c</id>
        <name>Mercury</name>
        <street>15976 Northland Court</street>
        <city>Chambéry</city>
        <region>Rhône-Alpes</region>
        <country>France</country>
        <carModels>
            <id>9fdf5b78-a4f6-421d-bb31-7905659148f4</id>
            <name>Integra</name>
            <year>1992</year>
            <usdPrice>$85390.20</usdPrice>
            <cadPrice>$49759.47</cadPrice>
            <euroPrice>€35901,90</euroPrice>
            <poundPrice>£36175.29</poundPrice>
        </carModels>
        <carModels>
            <id>7eb6db6a-3e5f-4f45-9868-abc9147c07f4</id>
            <name>F-Series</name>
            <year>2010</year>
            <usdPrice>$51991.77</usdPrice>
            <cadPrice>$86337.76</cadPrice>
            <euroPrice>€64038,87</euroPrice>
            <poundPrice>£87952.16</poundPrice>
        </carModels>
        <carModels>
            <id>d1509dec-8127-4c19-af56-351e7a0f6e03</id>
            <name>G</name>
            <year>1993</year>
            <usdPrice>$97249.58</usdPrice>
            <cadPrice>$54509.86</cadPrice>
            <euroPrice>€52900,33</euroPrice>
            <poundPrice>£64395.40</poundPrice>
        </carModels>
        <cars>
            <vin>3FAHP0DC5AR079112</vin>
            <color>Fuscia</color>
            <buyer>alewens5@github.io</buyer>
        </cars>
        <cars>
            <vin>3GTU1YEJ3BG470763</vin>
            <color>Crimson</color>
            <buyer>sandrassy6@msn.com</buyer>
        </cars>
        <cars>
            <vin>1G4HE57Y88U127043</vin>
            <color>Aquamarine</color>
            <buyer>bvonwelden7@foxnews.com</buyer>
        </cars>
        <cars>
            <vin>WAUVT54B34N516039</vin>
            <color>Blue</color>
            <buyer>mwattam8@cmu.edu</buyer>
        </cars>
        <cars>
            <vin>5J8TB18239A146727</vin>
            <color>Pink</color>
            <buyer>mbenedicto9@netlog.com</buyer>
        </cars>
    </automotive>
    <automotive>
        <id>39c96929-c2fb-4018-987d-8ba1a5cb9f1a</id>
        <name>Ford</name>
        <street>28691 Beilfuss Way</street>
        <city>Namie</city>
        <country>Japan</country>
        <carModels>
            <id>aa63872b-a97a-4e37-b8ce-c5fa1c75e003</id>
            <name>Solara</name>
            <year>2005</year>
            <usdPrice>$69129.33</usdPrice>
            <cadPrice>$30047.56</cadPrice>
            <euroPrice>€20685,47</euroPrice>